#pragma once

// MAIUSCOLE, senza accenti
inline const char* const WORDS[] = {
    "CASA","GATTO","CANE","SCUOLA","PIZZA","MONDO","COMPUTER","PROGRAMMA",
    "GIOCO","TRENO","MACCHINA","LIBRO","MARE","MONTAGNA","CITTA","STRADA",
    "AMICO","AMORE","NUMERO","CODICE","VIAGGIO","BOTTIGLIA","FINESTRA","PORTA",
    "TAVOLO","SEDIA","LAMPADA","QUADERNO","MATITA","PENNA","ZAINO","CARTELLA","TELEFONO","OROLOGIO",
    "CALENDARIO","PARETE","SOFFITTO","PAVIMENTO","PORTAFOGLIO","CHIAVE","SERRATURA","GIARDINO","FIORE","ALBERO",
    "FORESTA","MELA","ARANCIA","BANANA","FRAGOLA","LIMONE","CAROTA","PATATA","POMODORO","PANE",
    "FORMAGGIO","LATTE","CIOCCOLATO","BICICLETTA","MOTOCICLETTA","AUTOMOBILE","AEROPLANO","ELICOTTERO","NAVE","SOTTOMARINO",
    "FIUME","LAGO","OCEANO","COLLINA","ISOLA","DESERTO","BOSCO","VULCANO","PIOGGIA","NEVE",
    "SOLE","LUNA","STELLA","CIELO","NUVOLA","ARCOBALENO","TEMPORALE","TUONO","FULMINE","VENTO",
    "CALORE","FREDDO","GHIACCIO","SABBIA","ROCCIA","PIETRA","MATTONE","CEMENTO","LEGNO","FERRO",
    "ACCIAIO","RAME","ORO","ARGENTO","VETRO","CARTA","PLASTICA","GOMMA","STOFFA","TESSUTO",
    "SCARPA","STIVALE","CAPPELLO","MAGLIONE","CAMICIA","GIACCA","PANTALONE","CINTURA","CALZINO","GUANTO",
    "OCCHIALI","BORSA","VALIGIA","OMBRELLO","PORTACHIAVI","PORTAPENNE","QUADRO","CORNICE","SPECCHIO","SCRIVANIA",
    "SCAFFALE","ARMADIO","CASSETTO","CREDENZA","FRIGORIFERO","FORNO","FORNELLO","LAVASTOVIGLIE","LAVATRICE","ASCIUGATRICE",
    "MICROONDE","TELEVISIONE","RADIO","ALTOPARLANTE","CUFFIE","PORTATILE","TASTIERA","MOUSE","MONITOR","STAMPANTE",
    "SCANNER","WEBCAM","CAVO","BATTERIA","CARICABATTERIE","PRESA","ADATTATORE","ROUTER","MODEM","INTERNET",
    "SITO","PASSWORD","UTENTE","ACCOUNT","PROFILO","MESSAGGIO","EMAIL","FILE","DIRECTORY","ARCHIVIO",
    "DOCUMENTO","IMMAGINE","VIDEO","AUDIO","MUSICA","CANZONE","FILM","CINEMA","TEATRO","MUSEO",
    "STADIO","PISCINA","PALESTRA","PARCO","ZOO","OSPEDALE","FARMACIA","TRIBUNALE","MUNICIPIO","BIBLIOTECA",
    "UNIVERSITA","ISTITUTO","UFFICIO","FABBRICA","NEGOZIO","SUPERMERCATO","MERCATO","RISTORANTE","PIZZERIA","BAR",
    "CAFFE","ALBERGO","OSTELLO","CAMPEGGIO","STAZIONE","AEROPORTO","PORTO","AUTOSTRADA","POSTA","FERROVIA",
    "BINARIO","TORNELLO","MAPPA","BUS","TAXI","TRAM","METRO","BICCHIERE","TAZZA","PIATTO",
    "FORCHETTA","COLTELLO","CUCCHIAIO","CARAFFA","BROCCA","TEIERA","CAFFETTIERA","PADELLA","PENTOLA","TAGLIERE",
    "APRISCATOLE","APRIBOTTIGLIE","FRUSTA","GRATTUGIA","TOSTAPANE","SPREMAGRUMI","CUCINA","SALA","CAMERA","BAGNO",
    "CORRIDOIO","BALCONE","TERRAZZO","DIVANO","POLTRONA","TAPPETO","TENDA","CUSCINO","LENZUOLO","COPERTA",
    "ARMADIETTO","COMODINO","LAMPADARIO","ASTUCCIO","DIARIO","AGENDA","CALCOLATRICE","RIGHELLO","TEMPERINO","EVIDENZIATORE",
    "PENNARELLO","PENNELLO","ACQUERELLO","TELA","CAVALLETTO","SCULTURA","STATUA","QUOTIDIANO","RIVISTA","LIBRETTO",
    "ROMANZO","POESIA","DISEGNO","MATTINA","POMERIGGIO","SERA","NOTTE","ALBA","TRAMONTO","ORIZZONTE"

};

inline const int WORDS_N = static_cast<int>(sizeof(WORDS) / sizeof(WORDS[0]));
