name: Windows Release (Qt via aqt)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]   # cambia se il tuo branch è diverso

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      QT_VERSION: 6.5.3                # puoi mettere 6.6.3 o 6.7.2 se preferisci
      QT_ARCH: msvc2022_64             # MSVC 2022 x64
      APP_NAME: Giochiamo.exe           # ⬅️ CAMBIA se il tuo eseguibile ha un altro nome

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Python stabile + aqtinstall
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install aqtinstall
        run: |
          python -m pip install --upgrade pip
          python -m pip install "aqtinstall==3.2.5"

      # Scarica Qt per Windows (host) con aqt
      - name: Download Qt
        shell: pwsh
        run: |
          $qtRoot = Join-Path $env:RUNNER_TEMP "Qt"
          python -m aqt install-qt windows desktop $env:QT_VERSION $env:QT_ARCH -O $qtRoot
          echo "QT_DIR=$qtRoot\$env:QT_VERSION\$env:QT_ARCH" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Show Qt tools
        shell: pwsh
        run: |
          Write-Host "QT_DIR=$env:QT_DIR"
          Get-ChildItem "$env:QT_DIR\bin" | Select-Object Name | Out-String | Write-Host

      # Configura CMake puntando a Qt scaricato
      - name: Configure (CMake VS2022 x64)
        run: >
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="%QT_DIR%"

      - name: Build
        run: cmake --build build --config Release

      - name: Install to staging dir
        run: cmake --install build --config Release --prefix build/install

      # Verifica che l'eseguibile esista
      - name: Verify exe exists
        shell: pwsh
        run: |
          $exe = Join-Path "build/install" $env:APP_NAME
          if (-not (Test-Path $exe)) {
            Write-Host "Contenuto build/install:"
            Get-ChildItem -Recurse build/install | ForEach-Object { $_.FullName }
            throw "Eseguibile non trovato in build/install. Controlla il nome del target o l'install() in CMake."
          }

      # Esegue windeployqt dal Qt scaricato con aqt
      - name: Bundle Qt DLLs (windeployqt)
        shell: pwsh
        run: |
          $exe = Join-Path "build/install" $env:APP_NAME
          & "$env:QT_DIR\bin\windeployqt.exe" --release --compiler-runtime $exe

      - name: Zip portable folder
        run: powershell Compress-Archive -Path build\install\* -DestinationPath giochino-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: giochino-windows
          path: giochino-windows.zip
